### ISSUE TITLE
Add an OIDC default group

### ISSUE THREAD

**Issue by robertlagrant** [stevespringett/Alpine#411]
It's quite possible that the group management for some applications may happen mostly inside the application itself - not every organisation has the slick automation (xor the slow bureacracy) to manage teams purely in AD / Okta / etc.

For organisations that are happy to manage users within an application, it would be useful to be able to assign a default group to give a good first-login experience, that allows application administrators to grab that user and level their permissions or team memberships appropriately.

Suggest the framework adds a new environment variable:
 - OIDC_TEAMS_DEFAULT (string, cannot be present if OIDC_TEAMS_CLAIM is is present)

And any user profile's groups list will be set as a list containing this string.

**Comment by raboof** [comment]
> And any user profile's groups list will be set as a list containing this string.

If I understand the code correctly, the teams from the claim are synced on each login: non-matching teams are removed, matching teams are added.

For the proposed `OIDC_TEAMS_DEFAULT`, if the teams are manually changed by and aministrator, I'd say those changes should persist and not be overwritten on the next login. So perhaps a sensible behavior is: if no teams are associated with this user yet, add the team(s) from `OIDC_TEAMS_DEFAULT`. Otherwise, leave the teams untouched.

This has the (arguable) downside that if you _change_ `OIDC_TEAMS_DEFAULT`, existing accounts that are associated with 'old' default team will not be updated to switch to this 'new' default team. That seems reasonable to me, though.
